### ISSUE TITLE
CSS border-box on all elemets causes UI to break

### ISSUE THREAD

**Issue by hitautodestruct** [mozilla/togetherjs#470]
Setting [border-box on all elements](http://paulirish.com/2012/box-sizing-border-box-ftw/) in a page breaks the towtruck layout.

If this code is on my page:

``` css
*, *:after, *:before {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-sizing;
  box-sizing: border-box;
}
```

Then tow truck looks like this:
![image](https://f.cloud.github.com/assets/687730/443313/b565717c-b17a-11e2-92f9-282d3cea7fe2.png)

This can be fixed with a default setting for all elements:

``` css
*, *:after, *:before {
  -moz-box-sizing: content-box;
  -webkit-box-sizing: content-sizing;
  box-sizing: content-box;
}
```
